### ISSUE TITLE
Generating of manifest-bundle.zip is not working

### ISSUE THREAD

**Issue by VladFernoaga** [UI5Lab/UI5Lab-library-simple#11]
Hi,

I noticed that the issue (https://github.com/SAP/ui5-builder/issues/144) for generating the manifest-bundle.zip is closed and the tooling supports now generation of manifest-bundle.zip file.

I updated the dependencies in the package.json for ui5/cli to 1.4.0:
`
    "@ui5/cli": "^1.4.0",
`
and the build step to include manifest generation:
`
"build": "ui5 build --a --include-task=generateManifestBundle"
`
But after running the command:
` npm run build` 

I get following error

`
info builder:builder library ui5lab-library-simple � (3/8) Running task generateLibraryManifest                                                                                
modules\yazl\index.js:367:74)
info builder:builder library ui5lab-library-simple � (4/8) Running task generateManifestB ules\yazl\index.js:62:18)
undle...                                                                                  e_modules\@ui5\builder\lib\processors\bundlers\manifestBundler.js:106:8)
ERR! builder:builder Build failed in 1.45 min
Error: absolute path: /resources/ui5lab/geometry/manifest.json
    at validateMetadataPath (C:\work\git\UI5Lab-library-simple\node_modules\@ui5\cli\node_modules\yazl\index.js:367:74)modules\yazl\index.js:367:74)                                                             ules\yazl\index.js:62:18)
    at ZipFile.addBuffer (C:\work\git\UI5Lab-library-simple\node_modules\@ui5\cli\node_mode_modules\@ui5\builder\lib\processors\bundlers\manifestBundler.js:106:8)ules\yazl\index.js:62:18)
    at archiveContent.forEach (C:\work\git\UI5Lab-library-simple\node_modules\@ui5\cli\nodbuilder\lib\processors\bundlers\manifestBundler.js:103:18)e_modules\@ui5\builder\lib\processors\bundlers\manifestBundler.js:106:8)
    at Map.forEach (<anonymous>)
    at Promise (C:\work\git\UI5Lab-library-simple\node_modules\@ui5\cli\node_modules\@ui5\builder\lib\processors\bundlers\manifestBundler.js:103:18)    at new Promise (<anonymous>)
    at Promise.all.then.then (C:\work\git\UI5Lab-library-simple\node_modules\@ui5\cli\node_modules\@ui5\builder\lib\processors\bundlers\manifestBundler.js:100:30)
    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:189:7)
`

I observed the for libraries like sap.ui.core or sap.m the generation of the bundle works fine.

Thanks in advance

**Comment by RandomByte** [comment]
This should be resolved with [UI5 CLI v1.5.3](https://github.com/SAP/ui5-cli/releases/tag/v1.5.3).

In this project you need to manually update to it by executing `npm install @ui5/cli@latest`.

**Comment by VladFernoaga** [comment]
This issue was tested with the mentioned version and  it works. 
Thanks :)
